
version: 0.0
os: linux
files:
  - source: /scripts
    destination: /var/www/html/scripts
hooks:
  BeforeInstall:
    - location: scripts/install-packages.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/test.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/install-wp.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/uninstall.sh
      timeout: 300
      runas: root
