name: ammaratef45Flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  avatar_glow: ^1.2.0
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0
  firebase_auth: ^0.18.1
  google_sign_in: ^4.5.1
  firebase_storage: ^5.0.0-dev.3
  flutter_markdown_editor: ^1.1.1
  url_launcher: ^5.7.2
  fluttertoast: ^7.1.1
  device_info: ^0.4.2+9
  image_picker: ^0.6.7+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/avatar.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
