name: CFN

on:
  workflow_dispatch:

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy stack to AWS
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: WordpressBlog
          template: wordpressCfn.json
          parameter-overrides: "AkismetKey=${{ secrets.AKISMET_KEY }},DBName=${{ secrets.DB_NAME }},DBUser=${{ secrets.DB_USER }},DBPassword=${{ secrets.DB_PASSWORD }}"
          no-fail-on-empty-changeset: "1"

