name: CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::835451110523:user/Github-Actions
          aws-region: us-east-2
      - name: Deploy stack to AWS
        uses: aws-actions/aws-cloudformation-github-deploy@v1.0.3
        with:
          name: wordpress-blog
          template: wordpressCfn.json
          parameter-overrides: "KeyName=myKey,InstanceType=t2.small,DBName=${{ secrets.DB_NAME }},DBUser=${{ secrets.DB_USER }},DBPassword=${{ secrets.DB_PASSWORD }},DBRootPassword=${{ secrets.DB_PASSWORD }}"
          no-fail-on-empty-changeset: "1"

